/* This file was generated by SableCC (http://www.sablecc.org/). */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Grammar.node;
using Grammar.lexer;
using Grammar.analysis;

namespace Grammar.parser {

public class ParserException : ApplicationException
{
    Token token;

    public ParserException(Token token, String  message) : base(message)
    {
        this.token = token;
    }

    public Token Token
    {
      get { return token; }
    }
}

internal class State
{
    internal int state;
    internal ArrayList nodes;

    internal State(int state, ArrayList nodes)
    {
        this.state = state;
        this.nodes = nodes;
    }
}

internal class TokenIndex : AnalysisAdapter
{
    internal int index;

    public override void CaseTNumber(TNumber node)
    {
        index = 0;
    }

    public override void CaseTAssign(TAssign node)
    {
        index = 1;
    }

    public override void CaseTPlus(TPlus node)
    {
        index = 2;
    }

    public override void CaseTBegin(TBegin node)
    {
        index = 3;
    }

    public override void CaseTIdentifier(TIdentifier node)
    {
        index = 4;
    }

    public override void CaseEOF(EOF node)
    {
        index = 5;
    }
}

public class Parser
{
    private Analysis ignoredTokens = new AnalysisAdapter();
    public Analysis IgnoredTokens
    {
      get { return ignoredTokens; }
    }

    protected ArrayList nodeList;

    private Lexer lexer;
    private Stack stack = new Stack();
    private int last_shift;
    private int last_pos;
    private int last_line;
    private Token last_token;
    private TokenIndex converter = new TokenIndex();
    private int[] action = new int[2];

    private const int SHIFT = 0;
    private const int REDUCE = 1;
    private const int ACCEPT = 2;
    private const int ERROR = 3;

    public Parser(Lexer lexer)
    {
        this.lexer = lexer;
    }

    private int GoTo(int index)
    {
        int state = State();
        int low = 1;
        int high = gotoTable[index].Length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private void Push(int numstate, ArrayList listNode)
    {
        this.nodeList = listNode;

        stack.Push(new State(numstate, this.nodeList));
    }

    private int State()
    {
        State s = (State) stack.Peek();
        return s.state;
    }

    private ArrayList Pop()
    {
        return (ArrayList) ((State) stack.Pop()).nodes;
    }

    private int Index(Switchable token)
    {
        converter.index = -1;
        token.Apply(converter);
        return converter.index;
    }

    public Start Parse()
    {
        Push(0, null);

        IList ign = null;
        while(true)
        {
            while(Index(lexer.Peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new TypedList(NodeCast.Instance);
                }

                ign.Add(lexer.Next());
            }

            if(ign != null)
            {
                ignoredTokens.SetIn(lexer.Peek(), ign);
                ign = null;
            }

            last_pos = lexer.Peek().Pos;
            last_line = lexer.Peek().Line;
            last_token = lexer.Peek();

            int index = Index(lexer.Peek());
            action[0] = actionTable[State()][0][1];
            action[1] = actionTable[State()][0][2];

            int low = 1;
            int high = actionTable[State()].Length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < actionTable[State()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > actionTable[State()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    action[0] = actionTable[State()][middle][1];
                    action[1] = actionTable[State()][middle][2];
                    break;
                }
            }

            switch(action[0])
            {
                case SHIFT:
        {
            ArrayList list = new ArrayList();
            list.Add(lexer.Next());
                        Push(action[1], list);
                        last_shift = action[1];
                    }
        break;
                case REDUCE:
                    switch(action[1])
                    {
                    case 0:
        {
      ArrayList list = New0();
      Push(GoTo(0), list);
        }
        break;
                    case 1:
        {
      ArrayList list = New1();
      Push(GoTo(1), list);
        }
        break;
                    case 2:
        {
      ArrayList list = New2();
      Push(GoTo(2), list);
        }
        break;
                    case 3:
        {
      ArrayList list = New3();
      Push(GoTo(2), list);
        }
        break;
                    case 4:
        {
      ArrayList list = New4();
      Push(GoTo(3), list);
        }
        break;
                    case 5:
        {
      ArrayList list = New5();
      Push(GoTo(3), list);
        }
        break;
                    case 6:
        {
      ArrayList list = New6();
      Push(GoTo(4), list);
        }
        break;
                    case 7:
        {
      ArrayList list = New7();
      Push(GoTo(4), list);
        }
        break;
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) lexer.Next();
                        PProgram node1 = (PProgram) ((ArrayList)Pop())[0];
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(last_token,
                        "[" + last_line + "," + last_pos + "] " +
                        errorMessages[errors[action[1]]]);
            }
        }
    }

    ArrayList New0()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TBegin tbeginNode2 = (TBegin)nodeArrayList1[0];
        List<PAssignment> listNode5 = new List<PAssignment>();
        List<PAssignment> listNode4 = (List<PAssignment>)nodeArrayList2[0];
        if ( listNode4 != null )
        {
            listNode5.AddRange(listNode4);
        }
        AAssignments passignmentsNode3 = new AAssignments (
              listNode5
        );
        AProgram pprogramNode1 = new AProgram (
              tbeginNode2,
              passignmentsNode3
        );
        nodeList.Add(pprogramNode1);
        return nodeList;
    }
    ArrayList New1()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList3 = (ArrayList) Pop();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TIdentifier tidentifierNode2 = (TIdentifier)nodeArrayList1[0];
        TAssign tassignNode3 = (TAssign)nodeArrayList2[0];
        PExpression pexpressionNode4 = (PExpression)nodeArrayList3[0];
        AAssignment passignmentNode1 = new AAssignment (
              tidentifierNode2,
              tassignNode3,
              pexpressionNode4
        );
        nodeList.Add(passignmentNode1);
        return nodeList;
    }
    ArrayList New2()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList3 = (ArrayList) Pop();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        PExpression pexpressionNode2 = (PExpression)nodeArrayList1[0];
        TPlus tplusNode3 = (TPlus)nodeArrayList2[0];
        PExpression pexpressionNode4 = (PExpression)nodeArrayList3[0];
        AAdditionExpression pexpressionNode1 = new AAdditionExpression (
              pexpressionNode2,
              tplusNode3,
              pexpressionNode4
        );
        nodeList.Add(pexpressionNode1);
        return nodeList;
    }
    ArrayList New3()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        PExpression pexpressionNode1 = (PExpression)nodeArrayList1[0];
        nodeList.Add(pexpressionNode1);
        return nodeList;
    }
    ArrayList New4()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TIdentifier tidentifierNode2 = (TIdentifier)nodeArrayList1[0];
        AIdentifierExpression pexpressionNode1 = new AIdentifierExpression (
              tidentifierNode2
        );
        nodeList.Add(pexpressionNode1);
        return nodeList;
    }
    ArrayList New5()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TNumber tnumberNode2 = (TNumber)nodeArrayList1[0];
        AValueExpression pexpressionNode1 = new AValueExpression (
              tnumberNode2
        );
        nodeList.Add(pexpressionNode1);
        return nodeList;
    }
    ArrayList New6()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        List<PAssignment> listNode2 = new List<PAssignment>();
        PAssignment passignmentNode1 = (PAssignment)nodeArrayList1[0];
        if ( passignmentNode1 != null )
        {
            listNode2.Add(passignmentNode1);
        }
        nodeList.Add(listNode2);
        return nodeList;
    }
    ArrayList New7()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        List<PAssignment> listNode3 = new List<PAssignment>();
        List<PAssignment> listNode1 = (List<PAssignment>)nodeArrayList1[0];
        PAssignment passignmentNode2 = (PAssignment)nodeArrayList2[0];
        if ( listNode1 != null )
        {
            listNode3.AddRange(listNode1);
        }
        if ( passignmentNode2 != null )
        {
            listNode3.Add(passignmentNode2);
        }
        nodeList.Add(listNode3);
        return nodeList;
    }

    private static int[][][] actionTable = {
      new int[][] {
        new int[] {-1, 3, 0},
        new int[] {3, 0, 1},
      },
      new int[][] {
        new int[] {-1, 3, 1},
        new int[] {4, 0, 3},
      },
      new int[][] {
        new int[] {-1, 3, 2},
        new int[] {5, 2, -1},
      },
      new int[][] {
        new int[] {-1, 3, 3},
        new int[] {1, 0, 6},
      },
      new int[][] {
        new int[] {-1, 1, 6},
      },
      new int[][] {
        new int[] {-1, 1, 0},
        new int[] {4, 0, 3},
      },
      new int[][] {
        new int[] {-1, 3, 6},
        new int[] {0, 0, 8},
        new int[] {4, 0, 9},
      },
      new int[][] {
        new int[] {-1, 1, 7},
      },
      new int[][] {
        new int[] {-1, 1, 5},
      },
      new int[][] {
        new int[] {-1, 1, 4},
      },
      new int[][] {
        new int[] {-1, 1, 1},
      },
      new int[][] {
        new int[] {-1, 1, 3},
        new int[] {2, 0, 12},
      },
      new int[][] {
        new int[] {-1, 3, 12},
        new int[] {0, 0, 8},
        new int[] {4, 0, 9},
      },
      new int[][] {
        new int[] {-1, 1, 2},
      },
    };

    private static int[][][] gotoTable  = {
      new int[][] {
        new int[] {-1, 2},
      },
      new int[][] {
        new int[] {-1, 4},
        new int[] {5, 7},
      },
      new int[][] {
        new int[] {-1, 10},
        new int[] {12, 13},
      },
      new int[][] {
        new int[] {-1, 11},
      },
      new int[][] {
        new int[] {-1, 5},
      },
    };

    private static String[] errorMessages = {
      "expecting: 'begin'",
      "expecting: identifier",
      "expecting: EOF",
      "expecting: '='",
      "expecting: identifier, EOF",
      "expecting: number, identifier",
      "expecting: '+', identifier, EOF",
    };

    private static int[] errors = {
      0, 1, 2, 3, 4, 4, 5, 4, 6, 6, 4, 6, 5, 4, 
    };
}
}
