using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SablePP.Tools.Generate.CSharp
{
    /// <summary>
    /// Defines a collection of methods for emitting the 'imperative part' of C# code.
    /// The code emitted to the <see cref="ExecutableElement"/> is inserted into an internal <see cref="PatchElement"/>.
    /// In a derived class; use the <see cref="ExecutableElement.InsertContents"/> to determine where the contents should be location.
    /// </summary>
    public abstract class ExecutableElement : CSharpElement
    {
        private PatchElement contents;

        /// <summary>
        /// Initializes a new instance of the <see cref="ExecutableElement"/> class.
        /// </summary>
        protected ExecutableElement()
        {
            this.contents = new PatchElement();
        }

        /// <summary>
        /// Inserts the contents element that holds the code generated by this <see cref="ExecutableElement"/>.
        /// </summary>
        protected void InsertContents()
        {
            insertElement(contents);
        }

        /// <summary>
        /// Emits curly bracket, newline and increases indentation
        /// </summary>
        public void EmitBlockStart()
        {
            contents.Emit("{", UseSpace.Never, UseSpace.Never);
            contents.EmitNewLine();
            contents.IncreaseIndentation();
        }
        /// <summary>
        /// Decreases indentation, and emits curly bracket and newline
        /// </summary>
        public void EmitBlockEnd()
        {
            contents.DecreaseIndentation();
            contents.Emit("}", UseSpace.Never, UseSpace.Never);
            contents.EmitNewLine();
        }

        /// <summary>
        /// Emits the 'this' keyword at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitThis()
        {
            contents.Emit("this", UseSpace.NotPreferred, UseSpace.NotPreferred);
        }
        /// <summary>
        /// Emits the 'throw' keyword at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitThrow()
        {
            contents.Emit("throw", UseSpace.NotPreferred, UseSpace.Preferred);
        }
        /// <summary>
        /// Emits the 'new' keyword at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitNew()
        {
            contents.Emit("new", UseSpace.NotPreferred, UseSpace.Preferred);
        }
        /// <summary>
        /// Emits an identifier at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitIdentifier(string name)
        {
            contents.Emit(name, UseSpace.NotPreferred, UseSpace.Preferred);
        }
        /// <summary>
        /// Emits a period at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitPeriod()
        {
            contents.Emit(".", UseSpace.Never, UseSpace.Never);
        }
        /// <summary>
        /// Emits a comma at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitComma()
        {
            contents.Emit(",", UseSpace.Never, UseSpace.Preferred);
        }
        /// <summary>
        /// Emits the '=' operator at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitAssignment()
        {
            contents.Emit("=", UseSpace.Always, UseSpace.Always);
        }
        /// <summary>
        /// Emits the 'return' keyword at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitReturn()
        {
            contents.Emit("return", UseSpace.NotPreferred, UseSpace.Preferred);
        }
        /// <summary>
        /// Emits the 'yield' keyword at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitYield()
        {
            contents.Emit("yield", UseSpace.NotPreferred, UseSpace.Preferred);
        }
        /// <summary>
        /// Emits the 'dynamic' keyword at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        /// <param name="inparenthesis">if set to <c>true</c> the keyword is wrapped in parenthesis - '(dynamic)' instead of 'dynamic'.</param>
        public void EmitDynamic(bool inparenthesis = false)
        {
            if (inparenthesis)
                contents.Emit("(dynamic)", UseSpace.Never, UseSpace.Never);
            else
                contents.Emit("dynamic", UseSpace.NotPreferred, UseSpace.Preferred);
        }
        public ParenthesisElement EmitTypeOf()
        {
            EmitIdentifier("typeof");
            return EmitParenthesis();
        }

        public ParenthesisElement EmitIf()
        {
            contents.Emit("if", UseSpace.NotPreferred, UseSpace.Always);
            return EmitParenthesis();
        }
        public void EmitElse()
        {
            contents.Emit("else", UseSpace.NotPreferred, UseSpace.Preferred);
        }
        public ParenthesisElement EmitWhile()
        {
            contents.Emit("while", UseSpace.NotPreferred, UseSpace.Always);
            return EmitParenthesis();
        }
        public ParenthesisElement EmitFor()
        {
            contents.Emit("for", UseSpace.NotPreferred, UseSpace.Always);
            return EmitParenthesis();
        }
        public ParenthesisElement EmitUsing()
        {
            contents.Emit("using", UseSpace.NotPreferred, UseSpace.Always);
            return EmitParenthesis();
        }

        public ParenthesisElement EmitParenthesis(ParenthesisElement.Types type = ParenthesisElement.Types.Round)
        {
            ParenthesisElement par = new ParenthesisElement(type);
            contents.InsertElement(par);
            return par;
        }

        /// <summary>
        /// Emits the '!' operator at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitLogicNot()
        {
            contents.Emit("!", UseSpace.NotPreferred, UseSpace.Never);
        }
        /// <summary>
        /// Emits the '&&' operator at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitLogicAnd()
        {
            contents.Emit("&&", UseSpace.Always, UseSpace.Always);
        }
        /// <summary>
        /// Emits the '||' operator at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitLogicOr()
        {
            contents.Emit("||", UseSpace.Always, UseSpace.Always);
        }

        /// <summary>
        /// Emits the '&' operator at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitBinaryAnd()
        {
            contents.Emit("&", UseSpace.Always, UseSpace.Always);
        }
        /// <summary>
        /// Emits the '|' operator at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitBinaryOr()
        {
            contents.Emit("|", UseSpace.Always, UseSpace.Always);
        }
        /// <summary>
        /// Emits the '^' operator at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitBinaryXor()
        {
            contents.Emit("^", UseSpace.Always, UseSpace.Always);
        }

        /// <summary>
        /// Emits the '==' operator at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitEqual()
        {
            contents.Emit("==", UseSpace.Always, UseSpace.Always);
        }
        /// <summary>
        /// Emits the '!=' operator at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitNotEqual()
        {
            contents.Emit("!=", UseSpace.Always, UseSpace.Always);
        }
        /// <summary>
        /// Emits the '&gt;' operator at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitGreaterThan()
        {
            contents.Emit(">", UseSpace.Always, UseSpace.Always);
        }
        /// <summary>
        /// Emits the '&gt;=' operator at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitGreaterThanOrEqual()
        {
            contents.Emit(">=", UseSpace.Always, UseSpace.Always);
        }
        /// <summary>
        /// Emits the '&lt;' operator at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitLessThan()
        {
            contents.Emit("<", UseSpace.Always, UseSpace.Always);
        }
        /// <summary>
        /// Emits the '&lt;=' operator at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitLessThanOrEqual()
        {
            contents.Emit("<=", UseSpace.Always, UseSpace.Always);
        }

        /// <summary>
        /// Emits the '+' operator at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitPlus()
        {
            contents.Emit("+", UseSpace.Always, UseSpace.Always);
        }
        /// <summary>
        /// Emits the '-' operator at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitMinus()
        {
            contents.Emit("-", UseSpace.Always, UseSpace.Always);
        }

        /// <summary>
        /// Emits the '++' operator at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitPlusPlus()
        {
            contents.Emit("++", UseSpace.Never, UseSpace.NotPreferred);
        }
        /// <summary>
        /// Emits the '--' operator at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitMinusMinus()
        {
            contents.Emit("--", UseSpace.Never, UseSpace.NotPreferred);
        }

        /// <summary>
        /// Emits the 'as' keyword at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitAs()
        {
            contents.Emit("as", UseSpace.Always, UseSpace.Always);
        }
        /// <summary>
        /// Emits the 'is' keyword at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitIs()
        {
            contents.Emit("is", UseSpace.Always, UseSpace.Always);
        }

        /// <summary>
        /// Emits the 'true' keyword at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitTrue()
        {
            EmitIdentifier("true");
        }
        /// <summary>
        /// Emits the 'false' keyword at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitFalse()
        {
            EmitIdentifier("false");
        }
        /// <summary>
        /// Emits the 'null' keyword at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitNull()
        {
            EmitIdentifier("null");
        }

        /// <summary>
        /// Emits an integer value at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitIntValue(int value)
        {
            contents.Emit(value.ToString(), UseSpace.NotPreferred, UseSpace.NotPreferred);
        }
        /// <summary>
        /// Emits a floating point value (including the 'f') at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitFloatValue(float value)
        {
            contents.Emit(value.ToString("0,0") + "f", UseSpace.NotPreferred, UseSpace.NotPreferred);
        }
        /// <summary>
        /// Emits a string (wrapped in "-symbols) at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitStringValue(string text)
        {
            contents.Emit("\"" + text.Replace("\"", "\"\"") + "\"", UseSpace.NotPreferred, UseSpace.NotPreferred);
        }

        /// <summary>
        /// Emits the 'int' keyword at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitInt()
        {
            contents.Emit("int", UseSpace.NotPreferred, UseSpace.Preferred);
        }
        /// <summary>
        /// Emits the 'float' keyword at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitFloat()
        {
            contents.Emit("float", UseSpace.NotPreferred, UseSpace.Preferred);
        }
        /// <summary>
        /// Emits the 'string' keyword at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        public void EmitString()
        {
            contents.Emit("string", UseSpace.NotPreferred, UseSpace.Preferred);
        }

        /// <summary>
        /// Emits a new line at the end of this <see cref="ExecutableElement"/>.
        /// </summary>
        public void EmitNewLine()
        {
            contents.EmitNewLine();
            OnNewLineEmitted();
        }
        /// <summary>
        /// Emits a semicolon at the end of this <see cref="ExecutableElement"/>s content.
        /// </summary>
        /// <param name="newline">if set to <c>true</c> a new line is inserted after the semicolon.</param>
        public void EmitSemicolon(bool newline)
        {
            contents.Emit(";", UseSpace.Never, UseSpace.Preferred);
            if (newline)
                this.EmitNewLine();
        }

        public void IncreaseIndentation()
        {
            contents.IncreaseIndentation();
        }
        public void DecreaseIndentation()
        {
            contents.DecreaseIndentation();
        }

        protected virtual void OnNewLineEmitted()
        {
        }
    }
}
